### ISSUE TITLE
Any plan to support that "old" windows native look and feel?

### ISSUE THREAD

**Issue by MassMessage** [andrejilderda/react-desktop#3]
I'm very interested in this library and got excited with this new version. But my current application needs also that old native look-and-feel window, like:

![image](https://user-images.githubusercontent.com/11813549/166315944-477ca2b5-a7f5-44ee-91a3-258e898f0d01.png)

is this going to be supported? I could try do it myself and contribute to this project but my css skills are very low.

**Comment by andrejilderda** [comment]
Hi @MassMessage, I'd love it for nostalgia reasons, but this library won't support it officially. It should be possible to tweak it that way though. ;)

**Comment by MassMessage** [comment]
> 

Sadly i need to match the system's native look-and-feel as possible otherwise i wouldn't mind at all stick with the new one. Now, how hard would be to tweak it tho?

**Comment by andrejilderda** [comment]
Usually the app shell (like the screenshot you provided) is not the problem, since wrappers like Electron and Tauri provide ways to use the system's default. That means that the main concern is what is inside there. Can you provide a sample screenshot of that?

**Comment by MassMessage** [comment]
> Usually the app shell (like the screenshot you provided) is not the problem, since wrappers like Electron and Tauri provide ways to use the system's default. 

I didn't thought like this before... I was trying to have a window just like the windows regular with its native look-and-feel in one of the tabs in my application.  The thought of just make a regular window (electron's BrowserWindow) and I would get the the native look-and-feel was something I didn't think before. I could just use that but to archive what I want, I'd have to make that window(electron's BrowserWindow) as child of the Tab control (created with react). Is that possible? that would solve the problem elegantly, I guess

> That means that the main concern is what is inside there. 
the contents is filled by the user, dragging buttons into it

**Comment by andrejilderda** [comment]
No worries @MassMessage! Happy to hear you found a solution. That 7.css is pretty awesome!
